name: pr_completed

# this is a privileged workflow that can run with secrets
# to perform actions on work carried out in the pull_request workflow

on:
  workflow_run:
    workflows:
      - pr
    types:
      - completed

  workflow_call:
    inputs:
      version_tag:
        description: 'version tag to use(vx.x.x)'
        required: false
        default: "next_tag"
        type: string

  workflow_dispatch:
    inputs:
      version_tag:
        description: 'version tag to use(vx.x.x)'
        required: false
        default: "next_tag"
        type: string

jobs:
  unit_tests_report:
    uses: ./.github/workflows/unit_tests_report.yml

  merge_gatekeeper:
    runs-on: ubuntu-latest
    # Restrict permissions of the GITHUB_TOKEN.
    # Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        # NOTE: v1 is updated to reflect the latest v1.x.y. Please use any tag/branch that suits your needs:
        #       https://github.com/upsidr/merge-gatekeeper/tags
        #       https://github.com/upsidr/merge-gatekeeper/branches
        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - unit_tests_report
